- name: install apache
  package:
    name:
      - "{{ apache_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
